// Generated by CoffeeScript 1.7.1
$(function() {
  $("#intro .text, #intro .contact").fadeIn(2e3);
  $(".main").onepage_scroll({
    sectionContainer: "section",
    easing: "ease",
    animationTime: 1000,
    pagination: true,
    updateURL: false,
    beforeMove: function() {},
    afterMove: function() {},
    loop: false,
    keyboard: true,
    responsiveFallback: false
  });
});
